name: Build and publish docker images
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '1 8 * * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
#  build-ros_rpm_image:
#    name: Push Docker image to GitHub Packages
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: build rmf image and push to gh registry
#        uses: docker/build-push-action@v3
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          # update registry only during push to main and nightly build
#          #          push: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
#          push: true
#          tags: latest
#          context: dockers
#          file: dockers/ros_rpm.Dockerfile
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: dockers
          file: dockers/rmf_from_packages.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
